### ISSUE TITLE
Il sito non è ancora quello ufficiale.

### ISSUE THREAD

**Issue by gabridome** [assobit/assobit.github.io#11]
Il sito è live ma Assob.it punta ancora al sito vecchio. Il presente "issue" è aperto per raccogliere le eventuali obiezioni alla modifica di puntamento del dominio Assob.it dal sito vecchio al sito nuovo collegato a questo repository.

Alcune perplessità riguardanti la SEO sollevate da Paolo Dal Checco sono già state affrontate e non dovrebbero esserci problemi operando secondo le istruzioni suggerite da github e riportate per primo da Riccardo Casatta.

**Comment by capaccioli** [comment]
Esprimo il mio parere favorevole.

**Comment by RCasatta** [comment]
ACK

**Comment by giacomozucco** [comment]
Closed
