### ISSUE TITLE
La wiki page "idee, to do e progetti" sarebbe meglio gestita da qui

### ISSUE THREAD

**Issue by RCasatta** [assobit/assobit.github.io#12]
Come da oggetto, ogni punto della [wiki todo list](https://github.com/assobit/assobit.github.io/wiki/idee%2C-to-do-e-progetti) andrebbe gestita nella sezione issue, con vantaggi tra gli altri di poter scaturire una discussione su ogni punto e censire lo smarcamento dei punti

**Comment by gabridome** [comment]
ACK.
Dici di fare un issue per ogni punto?

**Comment by gabridome** [comment]
per ragioni a me sconosciute comunque nessun punto è stato incluso nel link
che hai mandato.
il link giusto è:
https://github.com/assobit/assobit.github.io/wiki/idee%2C-to-do-e-progetti

2016-01-05 15:23 GMT+01:00 Riccardo Casatta notifications@github.com:

> Come da oggetto, ogni punto della wiki todo list
> https://githubcom/assobit/assobitgithubio/wiki/idee%2C-to-do-e-progetti
> andrebbe gestita nella sezione issue, con vantaggi tra gli altri di poter
> scaturire una discussione su ogni punto e censire lo smarcamento dei punti
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/assobit/assobit.github.io/issues/12.

## 

Please avoid unnecessary attachments. Write in the body of the message.
Thank you.

Gabriele Domenichini
pgp fingerprint: DC47 A9B4 CF41 6373 6EBB  E14E A48F BF05 1C43 F817
Ƀ: https://greenaddress.it/it/pay/GA2zwPHGcVxy1MA79PKYPxrk672FrE/

**Comment by gabridome** [comment]
Ho inserto nella pagina la seguente prefazione:
UPDATE: su proposta di @RCasatta il tema in oggetto sarà trattato nelle issue del sito. I temi rimangono semplicemente citati qui fino a quando non sono stati compilati tutti gli issue.
